## 一、Python基础

### 1.列表生成式与条件赋值

In [4]:
# 在生成一个数字序列的时候，在 Python 中可以如下写出：
def my_func(x):
    return 2*x

# 1. 列表生成式得到数字序列

num_li = [my_func(i) for i in range(5)]
# 输出：[0, 2, 4, 6, 8]

# 2. 列表生成式支持多层嵌套
[m+'_'+n for m in 'abc' for n in 'cd']
# 输出 ['a_c', 'a_d', 'b_c', 'b_d', 'c_c', 'c_d']


['a_c', 'a_d', 'b_c', 'b_d', 'c_c', 'c_d']

In [6]:
# 3.带有if的条件赋值
# value = a if condition else b
value = 'cat' if 2 > 1 else 'dog'

# 截断列表中超过5的元素，即超过5的用5代替，小于5的保留原来的值：

L = [i if i<5 else 5 for i in range(11)]
# 输出：[0, 1, 2, 3, 4, 5, 5, 5, 5, 5, 5]

[0, 1, 2, 3, 4, 5, 5, 5, 5, 5, 5]

### 2、匿名函数与map方法

有一些函数的定义具有清晰简单的映射关系，例如上面的 my_func 函数，这时候可以用匿名函数的方法简洁地表示。

enumerate 是一种特殊的打包，它可以在迭代时绑定迭代元素的遍历序号。

既然有了压缩函数，那么 Python 也提供了 * 操作符和 zip 联合使用来进行解压操作。

In [11]:
my_func = lambda x: 2*x
my_func(2)
# 输出：4

# 实际使用不需要名字
[(lambda x: 2*x)(i) for i in range(5)]
# 输出： [0, 2, 4, 6, 8]

# 对于上述的这种列表推导式的匿名函数映射，
#  Python 中提供了 map 函数来完成，它返回的是一个 map 对象，
# 需要通过 list 转为列表：
list(map(lambda x: 2*x,range(5)))
# 输出：[0, 2, 4, 6, 8]

# 多个参数的情况
list(map(lambda x, y: str(x)+'_'+y, range(5),list('abcdw')))
# 输出：['0_a', '1_b', '2_c', '3_d', '4_w']


['0_a', '1_b', '2_c', '3_d', '4_w']

### 3、zip函数与enumerate方法

zip函数能够把多个可迭代对象打包成一个元组构成的可迭代对象，它返回了一个 zip 对象，通过 tuple, list 可以得到相应的打包结果：

In [14]:
L1, L2, L3 = list('abc'), list('def'), list('ghi')
list(zip(L1,L2,L3))
# 输出 [('a', 'd', 'g'), ('b', 'e', 'h'), ('c', 'f', 'i')]

tuple(zip(L1,L2,L3))
# 输出：(('a', 'd', 'g'), ('b', 'e', 'h'), ('c', 'f', 'i'))

# 在循环中使用zip函数
for i,j,k in zip(L1,L2,L3):
    print(i,j,k)
# 输出 
# a d g
# b e h
# c f i

a d g
b e h
c f i


In [16]:
# enumerate 是一种特殊的打包，它可以在迭代时绑定迭代元素的遍历序号：
L = list('abcd')

# (1)enumerate 可以指定起始序号 start=1
for index,value in enumerate(L,1):
    print(index,value)
# 输出
# 0 a
# 1 b
# 2 c
# 3 d

# (2)使用zip实现
for index,value in zip(range(len(L)),L):
    print(index,value)

# 需要对两个列表建立字典映射时，使用zip
dict(zip(L1,L2))
# 输出：{'a': 'd', 'b': 'e', 'c': 'f'}


1 a
2 b
3 c
4 d
0 a
1 b
2 c
3 d


{'a': 'd', 'b': 'e', 'c': 'f'}

In [21]:
# 既然有了压缩函数，那么 Python 也提供了 * 操作符和 zip 联合使用来进行解压操作：
zipped = list(zip(L1,L2,L3))
# 输出 ： [('a', 'd', 'g'), ('b', 'e', 'h'), ('c', 'f', 'i')]

list(zip(*zipped))
# 先把每一个元素提取出来，打散，然后使用zip拉链进行连接，最后得到3个列表
# 输出： [('a', 'b', 'c'), ('d', 'e', 'f'), ('g', 'h', 'i')]

[('a', 'b', 'c'), ('d', 'e', 'f'), ('g', 'h', 'i')]

# 二、Numpy基础

## 1、np数组的构造
最一般的方法是通过 array 来构造。

In [ ]:
import numpy as np

# (1)一般生成数组

np.array([1,2,3])
# 输出 array([1, 2, 3])

# (2) 特殊数组的生成方式
# a. 等差数列 np.linspace, np.arange
    # 起始，终点(包含)，元素个数
np_lin = np.linspace(1,5,5)
# print(f'linspace：{np_lin}')
# linspace：[1. 2. 3. 4. 5.]

    # 起始，终点(不包含)，步长
np_arange = np.arange(1,5,2)
# print(f'arange：{np_arange}')
# arange：[1 3]

# b.特殊矩阵 zeros,eye,full

# 全0矩阵 传入的元组表示各维度
np.zeros((2,3))

# 对角矩阵
np_eye = np.eye(3)
# array([[1., 0., 0.],
    #    [0., 1., 0.],
    #    [0., 0., 1.]])
np.eye(3,k=1) # 偏移主对角线1个单位的伪单位矩阵
# array([[0., 1., 0.],
#        [0., 0., 1.],
#        [0., 0., 0.]])

# full矩阵
np.full((2,3),10) # 2*3矩阵，10表示填充数值
# array([[10, 10, 10],
#        [10, 10, 10]])

# c.随机矩阵 np.random
# 最常用的随机生成函数为 rand, randn, randint, choice ，
# 它们分别表示0-1均匀分布的随机数组、标准正态的随机数组、随机整数组和随机列表抽样：

# <1>0-1均匀分布的随机数组
np.random.rand(3)  # 3个0-1之间的随机数
# array([0.76296156, 0.5197583 , 0.91569214])

np.random.rand(3,3)  # 3*3的0-1之间的随机数
# array([[0.39304238, 0.84983296, 0.62593311],
    #    [0.37114981, 0.90308621, 0.44126683],
    #    [0.23419655, 0.74558828, 0.3743816 ]])

# 对于服从区间 a 到 b 上的均匀分布可以如下生成：
a,b = 5 ,15
(b-a)* np.random.rand(3,2)+a
# 或者选择已有的库函数，如 np.random.uniform
np.random.uniform(5,15,(3,2))
# array([[12.84756072,  8.41917216],
    #    [ 8.55996346,  8.31066746],
    #    [ 8.30316769, 10.68261152]])

# <2>randn 标准正态分布的随机数组 
np.random.randn(3)
np.random.randn(3,3)

# 服从方程为 N(3,2.5) 均值为3，方差为2.5
sigma, mu = 2.5, 3
mu + np.random.randn(3) * sigma
# 或者调用库函数 np.random.normal
np.random.normal(3,2.5,(3,3)) # 均值为3，方差为2.5的3*3随机数组

# array([3.63085605, 5.79873192, 2.62285615])

# <3>randint 随机整数组
# randint 可以指定生成随机整数的最小值最大值（不包含）和维度大小：

low, high, size = 5, 15, (2,2)
np.random.randint(low,high,size)
# array([[14,  9],
    #    [14,  9]], dtype=int32)

# <4>choice 随机列表抽样
# choice 可以从给定的列表中，以一定概率和方式抽取结果，
# 当不指定概率时为均匀采样，默认抽取方式为有放回抽样：

my_list = list('abcd')

# 给定列表，抽取2个元素，不重复/不放回，每个元素的概率为0.1,0.2,0.3,0.4
np.random.choice(my_list,2,replace=False,p=[0.1,0.2,0.3,0.4])
# array(['b', 'd'], dtype='<U1')

# 当返回的元素个数与原列表相同时，不放回抽样等价于使用 permutation 函数，即打散原列表：
np.random.permutation(my_list)
# array(['a', 'd', 'b', 'c'], dtype='<U1')

# <5>shuffle 随机打乱数组
# 当需要将数组内元素随机打乱时，可使用 shuffle 函数：

arr = np.arange(10)
np.random.shuffle(arr)
arr

# <5>随机种子
# 它能够固定随机数的输出结果
np.random.seed(100)
np.random.rand()

0.5434049417909654

## 2. np数组的变形与合并

【a】转置： T

In [46]:
np.zeros((2,3)).shape
# (2, 3)

np.zeros((2,3)).T.shape
# (3, 2)

(3, 2)

【b】合并操作： r_, c_

对于二维数组而言， r_ 和 c_ 分别表示上下合并和左右合并：

In [48]:
# 上下合并
np.r_[np.zeros((2,3)),np.zeros((2,3))]
# array([[0., 0., 0.],
    #    [0., 0., 0.],
    #    [0., 0., 0.],
    #    [0., 0., 0.]])

# 左右合并
np.c_[np.zeros((2,3)),np.zeros((2,3))]
# array([[0., 0., 0., 0., 0., 0.],
    #    [0., 0., 0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

一维数组和二维数组进行合并时，应当把其视作列向量，在长度匹配的情况下**只能够使用左右合并的 c_ 操作**：

In [ ]:
# 上下合并
np.r_[np.array([0,0]),np.zeros((2))]
# array([0., 0., 0., 0.])

# 左右合并
# np.c_[np.array([0, 0]), np.zeros((2, 3))]
# array([[0., 0., 0., 0.],
    #    [0., 0., 0., 0.]])

array([0., 0., 0., 0.])

【c】维度变换： reshape

reshape 能够帮助用户把原数组按照新的维度重新排列。在使用时有两种模式，分别为*C模式(默认)*和 F 模式，分别以逐行和逐列的顺序进行填充读取。

In [ ]:
target = np.arange(8).reshape(2,4)
# array([[0, 1, 2, 3],
    #    [4, 5, 6, 7]])

# 按照行读取和填充（默认）
target.reshape((4,2),order='C')
# array([[0, 1],
#        [2, 3],
#        [4, 5],
#        [6, 7]])

# 按照列读取和填充
target.reshape((4,2),order='F')
# array([[0, 2],
    #    [4, 6],
    #    [1, 3],
    #    [5, 7]])

# 特别地，由于被调用数组的大小是确定的， reshape 允许有一个维度存在空缺，此时只需填充-1即可：
target.reshape((-1,2))
# array([[0, 1],
    #    [2, 3],
    #    [4, 5],
    #    [6, 7]])

# 转换为一维数组
target.reshape(-1)
# array([0, 1, 2, 3, 4, 5, 6, 7])

array([0, 1, 2, 3, 4, 5, 6, 7])

## 3、np数组的切片与索引

数组的切片模式支持使用 slice 类型的 start:end:step 切片，还可以直接传入列表指定某个维度的索引进行切片：

In [ ]:
target = np.arange(9).reshape(3,3)
# array([[0, 1, 2],
#        [3, 4, 5],
#        [6, 7, 8]])

# 切片
target[:-1,[0,2]]

# 当数组维度为1维时，可以直接进行布尔索引
new = target.reshape(-1)
new[new>5]
# array([6, 7, 8])

array([6, 7, 8])

## 4、常用函数

为了简单起见，这里假设下述函数输入的数组都是一维的。

【a】 where

where 是一种条件函数，可以指定满足条件与不满足条件位置对应的填充值：

In [71]:
a = np.array([-1,1,1,0]).reshape((2,2))

# 对应位置为True时填充a对应元素，否则填充5
np.where(a>0,a,5)
# array([5, 1, 1, 5])

array([[5, 1],
       [1, 5]])

【b】 nonzero, argmax, argmin

这三个函数返回的都是索引， nonzero 返回非零数的索引， argmax, argmin 分别返回最大和最小数的索引：

In [ ]:
a = np.array([-2,-5,0,1,3,-1])

# 非零数的索引
# 
b = np.nonzero(a)
# (array([0, 1, 3, 4, 5]),)
# 根据索引取到对应的列表
a[b]

idx_max = a.argmax()

idx_min = a.argmin()
idx_min,idx_max
# (np.int64(1), np.int64(4))

(np.int64(1), np.int64(4))

【c】 any, all

any 指当序列至少 存在一个 True 或非零元素时返回 True ，否则返回 False

all 指当序列元素 全为 True 或非零元素时返回 True ，否则返回 False

In [87]:
a = np.array([0,1])

a.any()
# np.True_

a.all()
# np.False_

np.False_

【d】 cumprod, cumsum, diff

cumprod, cumsum 分别表示累乘和累加函数，返回同长度的数组， diff 表示和前一个元素做差，由于第一个元素为缺失值，因此在默认参数情况下，返回长度是原数组减1

In [ ]:
a = np.array([1,2,3])

# 累乘
a.cumprod()
# array([1, 2, 6])

# 累加
a.cumsum()
# array([1, 3, 6])

# 差
np.diff(a)


array([1, 1])

【e】 统计函数

常用的统计函数包括 max, min, mean, median, std, var, sum, quantile ，其中分位数计算是全局方法，因此**不能通过 array.quantile 的方法调用**：

In [ ]:
target = np.arange(6).reshape(2,-1)
# array([[0, 1, 2],
    #    [3, 4, 5]])

# 行的最大值
target.max(axis=1)
# array([2, 5])

# 列的最大值
target.max(axis=0)
# array([3, 4, 5])

np.quantile(target,0.5,axis=0)
# array([1.5, 2.5, 3.5])
np.quantile(target,0.5,axis=1)
# array([1., 4.])



array([1., 4.])

对于**协方差和相关系数**分别可以利用 cov, corrcoef 如下计算：

In [ ]:
target1 = np.array([1,3,5,9])

target2 = np.array([1,5,3,-9])

# 协方差
np.cov(target1,target2)
# array([[ 11.66666667, -16.66666667],
    #    [-16.66666667,  38.66666667]])

np.corrcoef(target1,target2)
# array([[ 1.        , -0.78470603],
    #    [-0.78470603,  1.        ]])

array([[ 1.        , -0.78470603],
       [-0.78470603,  1.        ]])

最后，需要说明二维 Numpy 数组中统计函数的 axis 参数，它能够进行某一个维度下的统计特征计算，当 axis=0 时结果为列的统计指标，当 axis=1 时结果为行的统计指标：

**建议用压缩为axis=0也就是行来理解，压缩为axis=1也就是列来理解**

In [ ]:
target = np.arange(1,10).reshape(3,-1)
# array([[1, 2, 3],
    #    [4, 5, 6],
    #    [7, 8, 9]])

# 按列求和
target.sum(0)
# array([12, 15, 18])
# 按行求和
target.sum(1)
# array([ 6, 15, 24])

array([ 6, 15, 24])

## 5. 广播机制
广播机制用于处理两个不同维度数组之间的操作，这里只讨论不超过两维的数组广播机制。

【a】标量和数组的操作

当一个标量和数组进行运算时，标量会自动把大小扩充为数组大小，之后进行逐元素操作：



In [ ]:
res = 3 * np.ones((2,2)) + 1
# array([[4., 4.],
#        [4., 4.]])

res = 1 / res
# array([[0.25, 0.25],
    #    [0.25, 0.25]])


array([[0.25, 0.25],
       [0.25, 0.25]])

【b】二维数组之间的操作

当两个数组维度完全一致时，使用对应元素的操作，否则会报错，除非其中的某个数组的维度是 m * 1 
 或者 
 1 * n ，那么会扩充其具有 1 
 的维度为另一个数组对应维度的大小。例如， 1 * 2
 数组和 3 * 2
 数组做逐元素运算时会把第一个数组扩充为 3 * 2
 ，扩充时的对应数值进行赋值。但是，需要注意的是，如果第一个数组的维度是 1 * 3
 ，那么由于在第二维上的大小不匹配且不为 1
 ，此时报错。

In [ ]:
res = np.ones((3,2))

res * np.array([[2,3]]) # 第二个数组扩充第一维度为3
# array([[2., 3.],
#        [2., 3.],
#        [2., 3.]])

res * np.array([[2], [3], [4]]) # 第二个数组扩充第二维度为2
# array([[2., 2.],
#        [3., 3.],
#        [4., 4.]])



np.array([[2]]).shape
# (1,1)

# 等价于两次扩充，第二个数组两个维度分别扩充为3和2
res * np.array([[2]])
# array([[2., 2.],
#        [2., 2.],
#        [2., 2.]])



array([[3., 3.],
       [3., 3.],
       [3., 3.]])

【c】一维数组与二维数组的操作

当一维数组 $A_k$
 与二维数组 $B_{m,n}$
 操作时，等价于把一维数组视作 $A_{1,k}$
 的二维数组，使用的广播法则与【b】中一致，当 $k!=n$
 且 k,n 
 都不是 1
 时报错。

In [ ]:
np.ones(3) + np.ones((2,3))
# array([[2., 2., 2.],
    #    [2., 2., 2.]])

np.ones(3) + np.ones((2, 1))
# array([[2., 2., 2.],
    #    [2., 2., 2.]])

np.ones(1) + np.ones((2, 3))
# array([[2., 2., 2.],
#        [2., 2., 2.]])
# np.ones(3).shape
# (3,)

array([[2., 2., 2.],
       [2., 2., 2.]])

## 6、 向量与矩阵的计算

【a】向量内积： dot

$a \cdot b = \sum_{i=1}^n a_ib_i$

In [ ]:
a = np.array([1,2,3])

b = np.array([1,3,5])

# 向量内积
a.dot(b)

np.int64(22)

【b】向量范数和矩阵范数 np.linalg.norm

在矩阵范数的计算中，最重要的是 ord 参数，可选值如下：

| ord   | 矩阵范数 (norm for matrices)         | 向量范数 (norm for vectors)              |
| ----- | ------------------------------------ | ---------------------------------------- |
| None  | Frobenius 范数                       | 2-范数（欧几里得范数）                   |
| 'fro' | Frobenius 范数 -相当于将矩阵“展平”成向量后的 2-范数。                      | 不适用（仅用于矩阵）                     |
| 'nuc' | 核范数（Nuclear norm）               | 不适用（仅用于矩阵）                     |
| inf   | 每行绝对值之和的最大值（即最大行和） | 最大绝对值（即 ∞-范数）                  |
| -inf  | 每行绝对值之和的最小值（即最小行和） | 最小绝对值（即 -∞-范数）                 |
| 0     | 不支持（无定义）                     | 非零元素个数（即 0-范数，衡量稀疏性）    |
| 1     | 每列绝对值之和的最大值（即最大列和） | （绝对值之和（1-范数）                 |
| -1    | 每列绝对值之和的最小值（即最小列和） | 同上（即 1-范数），但注意这里的 -1 并不表示负的1-范数，而是特殊定义|
| 2     | 2-范数（最大奇异值）                 | 2范数|
| -2    | 最小奇异值                           | 同2-范数|
| other | 不支持（仅适用于向量）               | 通用 p-范数：`sum(abs(x)**ord)**(1/ord)` |

---


In [ ]:
matrix_target = np.arange(4).reshape(-1,2)
# array([[0, 1],
    #    [2, 3]])

# 相当于将矩阵“展平”成向量后的 2-范数。如下两个计算结果一致。
np.linalg.norm(matrix_target,'fro')
# np.float64(3.7416573867739413)

np.linalg.norm(np.arange(4),2)
# np.float64(3.7416573867739413)

# 最大行和
np.linalg.norm(matrix_target, np.inf)
# np.float64(5.0)

np.float64(5.0)

In [ ]:
vector_target =  np.arange(4)
# array([0, 1, 2, 3])

# 最大元素
np.linalg.norm(vector_target, np.inf)
# np.float64(3.0)
vector_target.max()
# np.int64(3)

# 向量的2-范数
np.linalg.norm(vector_target, 2)
# np.float64(3.7416573867739413)

np.linalg.norm(vector_target, 3)
# np.float64(3.3019272488946263)

np.float64(3.3019272488946263)

【c】矩阵乘法： @

$$
[A_{m\times p} B_{p\times n}]_{ij} = \sum_{k=1}^{p} A_{ik} B_{kj}
$$


In [ ]:
a = np.arange(4).reshape(-1,2)
# [[0 1]
#  [2 3]]

b = np.arange(-4,0).reshape(-1,2)
# [[-4 -3]
#  [-2 -1]]

a@b
# array([[ -2,  -1],
    #    [-14,  -9]])

[[0 1]
 [2 3]] [[-4 -3]
 [-2 -1]]


array([[ -2,  -1],
       [-14,  -9]])

# 三、练习

## Ex1：利用列表推导式写矩阵乘法


In [1]:

# 一般的矩阵乘法根据公式，可以由三重循环写出：

M1 = np.random.rand(2,3)

M2 = np.random.rand(3,4)

# np.empty() 是 NumPy 中用于创建一个未初始化的数组的函数。
res = np.empty((M1.shape[0],M2.shape[1]))
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]

for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
        item = 0
        for k in range(M1.shape[1]):
            item += M1[i][k] * M2[k][j]
        res[i][j] = item

# (np.abs((M1@M2 - res) < 1e-15)).all() # 排除数值误差
# True
# 请将其改写为列表推导式的形式。

NameError: name 'np' is not defined

### EX1答案


In [141]:
M1 = np.random.rand(2,3)

M2 = np.random.rand(3,4)


res = [[sum([M1[i][k]*M2[k][j] for k in range(M1.shape[1])]) for j in range(M2.shape[1]) ] for i in range(M1.shape[0]) ] 
(np.abs((M1@M2 - res) < 1e-15)).all() 

np.True_

## Ex2：更新矩阵

设矩阵 $ A_{m \times n} $，现在对 $ A $ 中的每一个元素进行更新生成矩阵 $ B $，更新方法是：

$$
B_{ij} = A_{ij} \sum_{k=1}^{n} \frac{1}{A_{ik}}
$$

例如，下面的矩阵为 $ A $，则：
$$
B_{2,2} = 5 \times \left( \frac{1}{4} + \frac{1}{5} + \frac{1}{6} \right) = \frac{37}{12}
$$

请利用 **NumPy** 高效实现。

$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$


In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B2=[[sum([1/A[i][k] for k in range(A.shape[1])])*A[i][j] for j in range(A.shape[1])] for i in range(A.shape[0])]

t = (1/A).sum(1)
# [1.83333333 0.61666667 0.37896825]
# 升高维度
B3 = A*t.reshape(-1,1)
# array([[1.83333333, 3.66666667, 5.5       ],
#        [2.46666667, 3.08333333, 3.7       ],
#        [2.65277778, 3.03174603, 3.41071429]])

(np.abs((B2-B3) < 1e-15)).all() 
# np.True_

array([[1.83333333, 3.66666667, 5.5       ],
       [2.46666667, 3.08333333, 3.7       ],
       [2.65277778, 3.03174603, 3.41071429]])

## Ex3：卡方统计量

设矩阵 $ A_{m \times n} $，记  
$$
B_{ij} = \frac{(\sum_{p=1}^m A_{pj}) \times (\sum_{q=1}^n A_{iq})}{\sum_{p=1}^m \sum_{q=1}^n A_{pq}}
$$

定义卡方值如下：
$$
\chi^2 = \sum_{i=1}^{m} \sum_{j=1}^{n} \frac{(A_{ij} - B_{ij})^2}{B_{ij}}
$$

请利用 **NumPy** 对给定的矩阵 $ A $ 计算 $ \chi^2 $。

```python
In [145]: np.random.seed(0)

In [146]: A = np.random.randint(10, 20, (8, 5))
```



In [ ]:
np.random.seed(0)

A = np.random.randint(10, 20, (8, 5))

B = A.sum(axis=0,keepdims=True)*A.sum(axis=1,keepdims=True)/A.sum(keepdims=True)


# 参考答案
# B = 
c0 = A.sum(axis=0)
c1 = A.sum(axis=1)
print(c0)
print(c1)

print(c0*c1.reshape(-1,1))
#  NumPy 中：
# A.sum(1) 是形状 (8,) —— 它是一个一维数组，既不是列向量也不是行向量。
# A.sum(0) 是形状 (5,)

# A.sum(1) * A.sum(0)  # 错！(8,) * (5,) → 无法广播，会出错或结果不对

# .reshape(-1, 1)后
# A.sum(1).reshape(-1, 1) → shape (8, 1)
# A.sum(0) → shape (5,)
# 广播后

# (8, 1) * (5,) → (8, 1) * (5,) → 广播为 (8, 5)


# 方法一：使用 reshape
# 这里是广播，所以顺序不重要。
B1 =  A.sum(1).reshape(-1, 1) * A.sum(0)/ A.sum()
B1 =  A.sum(0) * A.sum(1).reshape(-1, 1) / A.sum()
# 方法二：使用 outer
B2 = np.outer(A.sum(1), A.sum(0)) / A.sum()

np.abs((B1-B2)<1e-10).all()
# True

# X_2 = ((A-B)**2 / B).sum()


# X_2

[120 111 129 116 101]
[68 73 80 79 85 61 67 64]
[[ 8160  7548  8772  7888  6868]
 [ 8760  8103  9417  8468  7373]
 [ 9600  8880 10320  9280  8080]
 [ 9480  8769 10191  9164  7979]
 [10200  9435 10965  9860  8585]
 [ 7320  6771  7869  7076  6161]
 [ 8040  7437  8643  7772  6767]
 [ 7680  7104  8256  7424  6464]]


np.True_

## Ex4：改进矩阵计算的性能

设 $ Z $ 为 $ m \times n $ 的矩阵，$ B $ 和 $ U $ 分别是 $ m \times p $ 和 $ p \times n $ 的矩阵，$ B_i $ 为 $ B $ 的第 $ i $ 行，$ U_j $ 为 $ U $ 的第 $ j $ 列。定义：

$$
R = \sum_{i=1}^{m} \sum_{j=1}^{n} \|B_i - U_j\|_2^2 Z_{ij}
$$

其中 $ \| \mathbf{a} \|_2^2 $ 表示向量 $ \mathbf{a} $ 的分量平方和 $ \sum_i a_i^2 $。

现有某人根据如下给定的样例数据计算 $ R $ 的值，请充分利用 **NumPy** 中的函数，基于此问题改进这段代码的性能。

```python
In [147]: np.random.seed(0)

In [148]: m, n, p = 100, 80, 50

In [149]: B = np.random.randint(0, 2, (m, p))

In [150]: U = np.random.randint(0, 2, (p, n))

In [151]: Z = np.random.randint(0, 2, (m, n))
```

```python
In [152]: def solution(B=B, U=U, Z=Z):
   .....:     L_res = []
   .....:     for i in range(m):
   .....:         for j in range(n):
   .....:             norm_value = ((B[i] - U[:, j]) ** 2).sum()
   .....:             L_res.append(norm_value * Z[i][j])
   .....:     return sum(L_res)
   .....: 

In [153]: solution(B, U, Z)
Out[153]: 100566
```

---


### Ex4答案

In [16]:
import numpy as np
np.random.seed(0)

m, n, p = 100, 80, 50

B = np.random.randint(0, 2, (m, p)) # 100,50

U = np.random.randint(0, 2, (p, n)) # 80,50

Z = np.random.randint(0, 2, (m, n))

# res = (((B**2).sum(1).reshape(-1,1) + (U**2).sum(0) - 2*B@U)*Z).sum()

# res
T = (B**2).sum(1).reshape(-1,1)
# (100, 1)
# T.shape

# 当乘1,80时,会广播为100,80
S = (U**2).sum(0)
# (80,)
# S.shape

# 每一项是B的第i行的行和 + U的第j列的列和 - 2倍的B的第i行和U的第j列的点积

C = T + S - 2*B@U

# (100, 80)

(C*Z).sum()


np.int64(100566)


## Ex5：连续整数的最大长度

输入一个整数的 NumPy 数组，返回其**严格递增连续整数子数组**的最大长度。

例如：
- 输入 `[1,2,5,6,7]`，`[5,6,7]` 是具有最大长度的递增连续整数子数组，因此输出 `3`
- 输入 `[3,2,1,2,3,4,6]`，`[1,2,3,4]` 是具有最大长度的递增连续整数子数组，因此输出 `4`

请充分利用 **NumPy** 的内置函数完成。（提示：考虑使用 `nonzero`、`diff` 函数）

---

✅ **说明**：
- 使用 `np.diff()` 可以快速判断相邻元素是否连续（差值为 1）。
- 使用 `np.nonzero()` 或 `np.where()` 找出断点位置，从而分割出所有连续段。

---

> 📌 提示代码思路（可选）：
>
> ```python
> import numpy as np
> 
> def max_consecutive_length(arr):
>  diff = np.diff(arr)
>  # 连续整数的差应为 1
>  is_consecutive = (diff == 1)
>  # 找到不连续的位置
>  breaks = np.where(is_consecutive == False)[0]
>  # 将数组按断点分割，计算每段长度
>  lengths = np.diff(np.concatenate(([0], breaks, [len(arr)])))
>  return int(lengths.max())
> ```